api = "0.2"

[buildpack]
id = "tech.atls.buildpacks.yarn-workspace"
version = "0.0.2"
name = "Yarn Workspace Buildpack"

[metadata]
include_files = ["buildpack.toml"]

[[order]]

[[order.group]]
id = "tech.atls.buildpacks.yarn-install"
version = "0.0.2"

[[order.group]]
id = "tech.atls.buildpacks.yarn-workspace-build"
version = "0.0.2"

[[order.group]]
id = "tech.atls.buildpacks.yarn-workspace-pack"
version = "0.0.2"

[[order.group]]
id = "tech.atls.buildpacks.yarn-workspace-start"
version = "0.0.2"
