api = "0.2"

[buildpack]
id = "tech.atls.buildpacks.node-start"
version = "0.0.1"
name = "Node Start Buildpack"

[metadata]
include_files = ["dist", "bin/build", "bin/detect", "buildpack.toml"]
pre_package = "yarn build"

[[stacks]]
id = "tech.atls.stacks.node"
