name: Tools

on:
  workflow_call:
    inputs:
      version:
        description: 'Tools yarn version'
        type: string
        required: true
    secrets:
      patToken:
        required: true

jobs:
  update:
    name: Update Tools
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 19

      - name: Install
        run: yarn install

      - name: Update
        run: yarn set version from tag ${{ inputs.version }}
        env:
          YARN_ENABLE_IMMUTABLE_INSTALLS: false

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GH_TOKEN }}
          commit-message: 'feat: update tools'
          title: 'feat: update tools'
          branch-suffix: random
          delete-branch: true
          body: |
            Update tools to ${{ inputs.version }}.
            
